name: Python application

on:
  - pull_request
  - push

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.python-version }}

    env:
      ID_INSTANCE: ${{ secrets.ID_INSTANCE }}
      API_TOKEN_INSTANCE: ${{ secrets.API_TOKEN_INSTANCE }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          python${{ matrix.python-version }} -m flake8 --extend-ignore E999 .
      - name: Test with pytest
        run: |
          pytest